### ISSUE TITLE
It looks like the "has_phenotype" edge between "premature menopause" and "addison disease" is inverted, but the edge label is not inverted.  

Instead, the edge label should be "is phenotype of" (the inverse of "has phenotype") 

BTE in ARAX looks correct direction wise



### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/DataGaps#6]
## Steps to reproduce:
search for Addison Disease
wait for full results to come back, namely from BTE
look for "Platinum" as a treatment for Addison Disease.  

## Screenshots:
Failed to upload screenshot.

**Comment by sierra-moxon** [comment]
<img width="1274" alt="Screen Shot 2022-09-14 at 12 30 55 PM" src="https://user-images.githubusercontent.com/4561292/190245801-3f71b353-b596-44c3-9a41-ec6896dfbb18.png">
<img width="929" alt="Screen Shot 2022-09-13 at 3 31 54 PM" src="https://user-images.githubusercontent.com/4561292/190245941-65c17d05-c3d9-4f37-8af3-16d1eec12ad2.png">

**Comment by gprice1129** [comment]
Thanks for posting this. I believe I found the issue but will not be applying the fix until after the relay. Below is a screenshot.

<img width="1058" alt="Screen Shot 2022-09-15 at 9 40 53 AM" src="https://user-images.githubusercontent.com/27593697/190462146-2edf5108-c079-484d-a4c8-d54e09e3e494.png">
